ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS sync_mode TEXT NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS sync_status TEXT NOT NULL DEFAULT 'idle',
  ADD COLUMN IF NOT EXISTS sync_error TEXT,
  ADD COLUMN IF NOT EXISTS sync_last_synced_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS sync_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'sync',
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_businesses_sync_status ON businesses (sync_status);
